### PR TITLE
Update Android Tutorial

### PR DESCRIPTION
**Pull request by LizenzFass78851**
### This fixes issue #51

Please check the commit so that any errors can be corrected. (typing errors, design of the images, functionality of the website by applying these commits)

am grateful for change requests if required by maintainer.

### CODE REVIEW

**Comment by haumacher** [comment]
Cool, thank you very much - I fixed some broken links - this is hard when you cannot test - but now looks good!

**Comment by haumacher** [comment]
If someone wants to test or cross-read, here is a test installation: https://phoneblock.net/pb-test/setup-android/

**Comment by LizenzFass78851** [comment]
> If someone wants to test or cross-read, here is a test installation: https://phoneblock.net/pb-test/setup-android/

It works

**Comment by haumacher** [comment]
Thanks for the contribution!

**Pull request merged**
